// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_save_subscription_index from "./routes/api/save-subscription/index.ts";
import * as $api_send_notification from "./routes/api/send-notification.ts";
import * as $api_test from "./routes/api/test.ts";
import * as $api_users_index from "./routes/api/users/index.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Subscribe from "./islands/Subscribe.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/save-subscription/index.ts": $api_save_subscription_index,
    "./routes/api/send-notification.ts": $api_send_notification,
    "./routes/api/test.ts": $api_test,
    "./routes/api/users/index.ts": $api_users_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Subscribe.tsx": $Subscribe,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
